language: ruby
rvm:
 - "2.0.0"
 - "2.1.7"
 - "2.2.3"
# uncomment this line if your project needs to run something other than `rake`:
before_script: bundle exec rspec
script: bundle exec middleman build

# script: bundle exec rspec spec