language: ruby
rvm:
- 2.0.0
cache: bundler
script:
  - bundle exec middleman build
after_success:
  - git config --global user.name ${GH_NAME}
  - git config --global user.email ${GH_EMAIL}
  - bundle exec middleman deploy

env:
  # global:
  #   - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  secure: "X04Lfl4+mnOQgLXJ6dFNlY5X/tlrm58lc3tkZgZ3t2a9rwV0oILHFe0OtRsxu1G9gLGYv4ZJm1vZdw726D5rKj4fzEYjX3Wq87TEunq+ItLRxiEYXTsMDE5Xfbibx//Sh4pZR7XfU5H1/Vte47ZNC4etICq2oTGGDyn+ryu7mwlGo3CXIqZc/zTmp54xtqMBhHNozwAz1Acblr2uHCS+UDChNzVSdwezVOnwwNUvFtvIBQVej66xIdRmB5vIJo4inF5p3ZbjOt/bvl/3JYqYKy1t0V0NRdGKkljjHc+e3bAvbIl/rTbZo5oixkDDILMeJf5RE53skDegkGrSnVRRxTAivPhh8OO9/MNgR4RK6K81PX2lmNOqOiagSwX/Izz0M2zokMQzDy2UqQmzUrPdAu7uOoyJ1vOcjNpfZNNd9qPUI651p6J7biBbRKxOK+rA3OzcHdkvwz91cbxxh+vhPycfPPtrk5UsyoeLQigWFtWEXcW9SeX7II9NlneEynNrGFQ7d6QC6dUmV1OuvAq5CVCzV8lb5p8eOJnih7sIPTN1NDou33Pj9l9I2QE0BL4YOb2X/eBLm8SpXV52kJKR/ILpmx0jSHSgFl8KEg9zml+AaiTgoe7DOEOmaY2LUhvFoNrEge8tQuJ66u+E/0FpZ/TrFsSF6cLuLvZ6llj6lBg="