language: ruby
rvm:
 - "2.0.0"

cache: bundler

# before_script:
#   - bundle update
script:
  - bundle exec middleman build
after_success:
  - rake travis_ci

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer