language: ruby
rvm:
 - "2.0.0"

cache: bundler

script:
  - bundle exec middleman build
after_success:
  - git config --global user.name ${GH_NAME}
  - git config --global user.email ${GH_EMAIL}
  - bundle exec middleman deploy

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer